### ISSUE TITLE
The current running results are all 0.

### ISSUE THREAD

**Issue by DXSHAN-NEU** [TongXin-CASIA/SiftFlow_feature#1]
Hello author, thank you very much. What about Kern_ x，kern_ y,kern_ h,kern_ v. Where can we find the theoretical basis for setting the value of? The current running results are all 0.

**Comment by TongXin-CASIA** [comment]
> Hello author, thank you very much. What about Kern_ x，kern_ y,kern_ h,kern_ v. Where can we find the theoretical basis for setting the value of? The current running results are all 0.

kern_x,kern_y are Laplace kernels and the kern_h, kern_v are Gaussian window kernel.
The result of the file is reasonable, please check your settings.
